name: FAST-VQA-M-VS
num_epochs: 30
l_num_epochs: 0
warmup_epochs: 2.5
ema: true
save_model: true
batch_size: 8
num_workers: 6

wandb:
    project_name: VQA_Experiments_2022

data:
    train:
        type: FusionDataset
        args:
            phase: train
            anno_file: ./examplar_data_labels/VSdataset/train_list.txt
            data_prefix: /your/data/path/VSdataset
            sample_types:
                resize:
                    size_h: 224
                    size_w: 224
                    clip_len: 32
                    frame_interval: 2
                    t_frag: 1
                    num_clips: 1

    val:
        type: FusionDataset
        args:
            phase: test
            anno_file: ./examplar_data_labels/VSdataset/val_list.txt
            data_prefix: /your/data/path/VSdataset
            sample_types:
                resize:
                    size_h: 224
                    size_w: 224
                    clip_len: 32
                    frame_interval: 2
                    t_frag: 1
                    num_clips: 4

    test:
        type: FusionDataset
        args:
            phase: test
            anno_file: ./examplar_data_labels/VSdataset/test_list.txt
            data_prefix: /your/data/path/VSdataset
            sample_types:
                resize:
                    size_h: 224
                    size_w: 224
                    clip_len: 32
                    frame_interval: 2
                    t_frag: 1
                    num_clips: 4
        
model:
    type: Stablev2Evaluator
    args:
        backbone:
            resize:
                checkpoint: false
                pretrained: 
        backbone_size: swinv1
        backbone_preserve_keys: resize
        divide_head: false
        vqa_head:
            in_channels: 768
            hidden_channels: 64
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05

load_path: ./pretrained_weights/swin_tiny_patch4_window7_224.pth
test_load_path: ./pretrained_weights/FAST-VQA-M-VS_val_n_dev_v1.0.pth
    
        

